/* ================================================================
UNKSCAPE HUD SPEC v10 hud_spec.js
Wires the spec HUD overlay to window.UnkScape.
No frameworks, no emoji, no scroll, no canvas resize on toggle.
================================================================ */
((US) => {
var INV_SLOT_COUNT=28,ACTION_SLOT_COUNT=6,LOG_MAX_LINES=60;
var SKILL_COLORS={combat:"#e74c3c",woodcutting:"#2ecc71",mining:"#95a5a6",fishing:"#3498db",herbalism:"#27ae60",hunting:"#e67e22",farming:"#f1c40f",smithing:"#e59866",cooking:"#ffcf6e",alchemy:"#8e44ad",crafting:"#6aa7ff",survival:"#ff9b5c",building_claim_crafting:"#cd6155",trading_merchanting:"#f7dc6f",extraction:"#1abc9c"};
var EQUIP_SLOTS=["weapon","shield","helmet","chest","legs","boots","gloves","cape","ring","amulet"];
var EQUIP_LABELS={weapon:"WPN",shield:"SHD",helmet:"HLM",chest:"CST",legs:"LGS",boots:"BTS",gloves:"GLV",cape:"CPE",ring:"RNG",amulet:"AMU"};
var _invTab="inv",_sysTab="all",_logLines=[],_radarCtx=null,_built=false,_hookTimer=null;
function _invSlotsHTML(){var h="";for(var i=0;i<INV_SLOT_COUNT;i++)h+='<div class="hi-slot empty" data-inv-slot="'+i+'"><span class="hi-ico"></span></div>';return h;}
function _skillCellsHTML(){var D=window.UnkScape;var skills=(D&&D.SKILLS)?Object.keys(D.SKILLS):["combat","woodcutting","mining","fishing","herbalism","hunting","farming","smithing","cooking","alchemy","crafting","survival","building_claim_crafting","trading_merchanting","extraction"];return skills.map(function(key){var def=(D&&D.SKILLS&&D.SKILLS[key])||{};var col=SKILL_COLORS[key]||"#94a3b8";return '<div class="hi-skill-cell" data-skill-key="'+key+'"><div class="hi-sk-name">'+(def.name||key)+'</div><div class="hi-sk-lv" style="color:'+col+'">Lv.01</div><div class="hi-sk-bar"><div class="hi-sk-fill" style="width:0%;background:'+col+'"></div></div></div>';}).join("");}
function _equipRowsHTML(){return EQUIP_SLOTS.map(function(s){return '<div class="hi-eq-row"><span class="hi-eq-slot">'+(EQUIP_LABELS[s]||s.slice(0,3).toUpperCase())+'</span><span class="hi-eq-val" data-eq-slot="'+s+'">—</span></div>';}).join("");}
function _paperDollHTML(){var sl=function(key,lbl){return '<div class="hed-slot" data-eq-slot="'+key+'" title="'+lbl+'"><span class="hed-lbl">'+lbl+'</span><span class="hed-val" data-hed-val="'+key+'"></span></div>';};var empty='<div class="hed-slot hed-empty"></div>';return ('<div class="hed-row">' + empty + sl("helmet","HLM") + empty + '</div>' +'<div class="hed-row">' + sl("cape","CPE") + sl("amulet","AMU") + sl("quiver","QVR") + '</div>' +'<div class="hed-row">' + sl("weapon","WPN") + sl("chest","CST") + sl("shield","SHD") + '</div>' +'<div class="hed-row">' + empty + sl("legs","LGS") + empty + '</div>' +'<div class="hed-row">' + sl("gloves","GLV") + sl("boots","BTS") + sl("ring","RNG") + '</div>');}
function _actionSlotsHTML(){var h="";for(var i=0;i<ACTION_SLOT_COUNT;i++)h+='<div class="ha-slot empty" data-action-slot="'+i+'"><span class="ha-num">'+(i+1)+'</span><span class="ha-ico"></span></div>';return h;}
function _buildHTML(){
var inv='<div id="hud-col-left">' +'<div id="hud-vitals" class="h-frame"><div class="h-inner" style="padding:10px;">' +'<div class="hv-name" id="hv-name">UNKSCAPE</div>' +'<div class="hv-race" id="hv-race">Human &middot; Oathstead</div>' +'<div class="hv-bars">' +'<div class="hv-bar-row"><span class="hv-bar-label">HP</span><div class="hv-bar-track"><div class="hv-bar-fill hp" id="hv-hp" style="width:78%"></div></div><span class="hv-bar-val" id="hv-hp-val">78%</span></div>' +'<div class="hv-bar-row"><span class="hv-bar-label">Stam</span><div class="hv-bar-track"><div class="hv-bar-fill stam" id="hv-stam" style="width:54%"></div></div><span class="hv-bar-val" id="hv-stam-val">54%</span></div>' +'<div class="hv-bar-row"><span class="hv-bar-label">Hung</span><div class="hv-bar-track"><div class="hv-bar-fill hung" id="hv-hung" style="width:80%"></div></div><span class="hv-bar-val" id="hv-hung-val">80%</span></div>' +'</div></div></div>' +'<div id="hud-inv" class="h-frame"><div class="h-inner">' +'<div class="h-header"><span class="h-gem h-gem-fire"></span>INVENTORY<span class="h-gem h-gem-ice" style="margin-left:auto;"></span></div>' +'<div class="hi-tabs"><button class="hi-tab active" data-tab="inv" onclick="UnkScape.HUDSpec._switchInvTab('\''inv'\'')">Inv</button><button class="hi-tab" data-tab="skills" onclick="UnkScape.HUDSpec._switchInvTab('\''skills'\'')">Skills</button><button class="hi-tab" data-tab="equip" onclick="UnkScape.HUDSpec._switchInvTab('\''equip'\'')">Equip</button></div>' +'<div class="hi-content"><div class="hi-pane active" id="hi-pane-inv"><div class="hi-slot-grid" id="hi-inv-grid">'+_invSlotsHTML()+'</div></div>' +'<div class="hi-pane" id="hi-pane-skills"><div class="hi-skills-grid" id="hi-skills-grid">'+_skillCellsHTML()+'</div></div>' +'<div class="hi-pane" id="hi-pane-equip"><div class="hi-equip-merged"><div class="hi-equip-text"><div class="hi-equip-list" id="hi-equip-list">'+_equipRowsHTML()+'</div></div><div class="hi-equip-doll"><div class="hed-grid" id="hed-grid">'+_paperDollHTML()+'</div></div></div></div></div>' +'</div></div></div>';
var ctr='<div id="hud-col-center">' +'<div id="hud-banner" class="h-frame"><div class="hb-inner"><div class="hb-gem h-gem h-gem-fire"></div><div><div class="hb-title">UNKSCAPE</div><div class="hb-sub" id="hb-sub">UNKSCAPE Sandbox MMORPG</div></div><div class="hb-gem h-gem h-gem-ice"></div></div></div>' +'<div id="hud-world-gap"></div>' +'<div id="hud-combat-strip"><div class="hcs-chip" id="hcs-atk">ATK: Tap Attack</div><div class="hcs-meter-wrap"><div class="hcs-meter-fill" id="hcs-meter"></div></div><div class="hcs-chip def" id="hcs-def">DEF: Guard</div><div class="hcs-chip" id="hcs-build">Build: Off</div></div>' +'<div id="hud-actionbar" class="h-frame"><div class="ha-inner" id="ha-slots">'+_actionSlotsHTML()+'</div></div>' +'</div>';
var rgt='<div id="hud-col-right">' +'<div id="hud-radar" class="h-frame"><div class="h-inner" style="align-items:center;padding:8px 4px;"><div class="h-header" style="width:100%;justify-content:space-between;"><span class="hr-n">N</span><span style="font-size:10px;letter-spacing:0.12em;">RADAR</span></div><div class="hr-canvas-wrap"><canvas id="hud-radar-canvas" width="140" height="140"></canvas></div></div></div>' +'<div id="hud-sysread" class="h-frame"><div class="h-inner"><div class="h-header">SYSTEM READOUT</div>' +'<div class="hsr-tabs"><button class="hsr-tab active" data-tab="all" onclick="UnkScape.HUDSpec._switchSysTab('\''all'\'')">All</button><button class="hsr-tab" data-tab="game" onclick="UnkScape.HUDSpec._switchSysTab('\''game'\'')">Game</button><button class="hsr-tab" data-tab="trade" onclick="UnkScape.HUDSpec._switchSysTab('\''trade'\'')">Trade</button></div>' +'<div class="hsr-log" id="hsr-log"></div>' +'<div class="hsr-input-row"><input class="hsr-input" id="hsr-input" type="text" placeholder="Say..." autocomplete="off"/><button class="hsr-send" id="hsr-send">Send</button></div>' +'</div></div></div>';
return inv+ctr+rgt;
}
US.HUDSpec={
init:function(){if(_built)return;_built=true;var r=document.createElement("div");r.id="unk-hud";r.setAttribute("data-hand","left");r.innerHTML=_buildHTML();document.body.appendChild(r);_wireActionBar();_wireSysInput();var rc=document.getElementById("hud-radar-canvas");_radarCtx=rc?rc.getContext("2d"):null;this.hide();setInterval(function(){window.UnkScape.HUDSpec.refresh();},1000);setInterval(function(){_drawRadar();},250);_watchState();_hookGameLog();this.log("System","system","Welcome to Oathstead Village.");console.log("[HUDSpec] v3 mounted, gated on game.state.");},setVisible:function(on){if(on)this.show();else this.hide();},show:function(){var h=document.getElementById("unk-hud");if(!h)return;h.classList.remove("hud-hidden");},hide:function(){var h=document.getElementById("unk-hud");if(!h)return;h.classList.add("hud-hidden");},log:function(sender,sc,msg){_logLines.push({sender:sender,senderClass:sc||"system",msg:msg});if(_logLines.length>LOG_MAX_LINES)_logLines.shift();_renderLog();},
refresh:function(){_updateVitals();_updateActionBar();if(_invTab==="inv")_updateInvSlots();if(_invTab==="skills")_updateSkillsPane();if(_invTab==="equip")_updateEquipPane();},
_switchInvTab:function(tab){_invTab=tab;["inv","skills","equip"].forEach(function(t){var p=document.getElementById("hi-pane-"+t);if(p)p.classList.toggle("active",t===tab);});document.querySelectorAll(".hi-tab").forEach(function(b){b.classList.toggle("active",b.dataset.tab===tab);});if(tab==="inv")_updateInvSlots();if(tab==="skills")_updateSkillsPane();if(tab==="equip")_updateEquipPane();},
_switchSysTab:function(tab){_sysTab=tab;document.querySelectorAll(".hsr-tab").forEach(function(b){b.classList.toggle("active",b.dataset.tab===tab);});_renderLog();}
};
function _wireActionBar(){var el=document.getElementById("ha-slots");if(!el)return;el.addEventListener("click",function(e){var s=e.target.closest("[data-action-slot]");if(!s)return;var idx=parseInt(s.dataset.actionSlot,10);var g=_game();if(g&&g.hotbar){g.hotbar.selected=idx;_updateActionBar();}});}
function _wireSysInput(){var btn=document.getElementById("hsr-send"),inp=document.getElementById("hsr-input");if(!btn||!inp)return;function send(){var v=inp.value.trim();if(!v)return;US.HUDSpec.log("You","player",v);inp.value="";}btn.addEventListener("click",send);inp.addEventListener("keydown",function(e){if(e.key==="Enter")send();});}
function _game(){var D=window.UnkScape;return(D&&D.game&&D.game.player)?D.game:null;}
function _updateVitals(){var g=_game(),D=window.UnkScape,ne=document.getElementById("hv-name"),re=document.getElementById("hv-race");if(!g){if(ne)ne.textContent="UNKSCAPE";if(re)re.textContent="No character loaded";return;}var p=g.player;if(ne)ne.textContent=(p.characterName||p.name||"Hero").toUpperCase();var fac=p.factionId==="blood_oath"?"Blood Oath":p.factionId==="highborn"?"Highborn":(p.factionName||"Wanderer");if(re)re.textContent=(p.raceId||"Human")+"·"+fac;var _hpMax=Math.round(p.maxHp||100);var _hpSafe=Math.min(Math.max(0,Math.ceil(p.hp||0)),_hpMax);_setBar("hv-hp","hv-hp-val",Math.round((_hpSafe/Math.max(1,_hpMax))*100),_hpSafe+"/"+_hpMax);var cl=(D&&D.levelForXp)?D.levelForXp(p.skills&&p.skills.combat?p.skills.combat.xp||0:0):1;var _stMax=Math.round(p.maxStamina||100);var _stSafe=Math.min(Math.max(0,Math.ceil(p.stamina||0)),_stMax);_setBar("hv-stam","hv-stam-val",Math.round((_stSafe/Math.max(1,_stMax))*100),_stSafe+"/"+_stMax);var hu=g.settings&&g.settings.hungerEnabled?Math.round(((p.hunger||80)/100)*100):100;_setBar("hv-hung","hv-hung-val",hu,hu+"%");var sub=document.getElementById("hb-sub");if(sub){var dn=g.systems&&g.systems.daynight;sub.textContent=dn?dn.label()+"· Day "+(Math.floor(g.time/dn.dayLength)+1):"UNKSCAPE Sandbox MMORPG";}var atk=document.getElementById("hcs-atk"),def=document.getElementById("hcs-def"),bld=document.getElementById("hcs-build"),mtr=document.getElementById("hcs-meter");if(atk){atk.textContent="ATK: "+(g.buildMode?"Place":p.heavyCharging?"Heavy":"Tap Attack");atk.classList.toggle("active",!!p.heavyCharging);}if(def)def.textContent="DEF: "+(g.buildMode?"Remove":p.blocking?"Guarding":"Guard");if(bld){bld.textContent="Build: "+(g.buildMode?"On":"Off");bld.classList.toggle("active",!!g.buildMode);}if(mtr){var ch=D&&D.clamp?D.clamp((p.heavyCharge||0)/Math.max(0.01,(g.systems.combat&&g.systems.combat.maxCharge||1.25)-(g.systems.combat&&g.systems.combat.heavyThreshold||0.72)),0,1)*100:0;mtr.style.width=ch+"%";}}
function _setBar(fi,vi,pct,lbl){var f=document.getElementById(fi),v=document.getElementById(vi);if(f)f.style.width=Math.max(0,Math.min(100,pct))+"%";if(v)v.textContent=lbl;}
function _updateInvSlots(){var g=_game(),D=window.UnkScape,grid=document.getElementById("hi-inv-grid");if(!grid)return;var slots=grid.querySelectorAll("[data-inv-slot]"),inv=g&&g.systems?g.systems.inventory:null,items=[];if(inv&&D&&D.ITEMS){for(var id in D.ITEMS){if(id==="coin")continue;var q=inv.count(id);if(q>0)items.push({id:id,qty:q});}}slots.forEach(function(el,i){var item=items[i],ico=el.querySelector(".hi-ico"),qty=el.querySelector(".hi-qty");if(!item){el.classList.add("empty");if(ico)ico.textContent="";if(qty)qty.remove();el.title="";return;}el.classList.remove("empty");var def=(D&&D.ITEMS&&D.ITEMS[item.id])||{name:item.id,icon:"?"};if(ico)ico.textContent=def.icon||"?";el.title=def.name||item.id;if(item.qty>1){if(!qty){qty=document.createElement("span");qty.className="hi-qty";el.appendChild(qty);}qty.textContent="x"+item.qty;}else if(qty){qty.remove();}el.classList.toggle("selected",g&&g.hotbar&&g.hotbar.selected===i);});}
function _updateSkillsPane(){var g=_game(),D=window.UnkScape,grid=document.getElementById("hi-skills-grid");if(!grid)return;grid.querySelectorAll("[data-skill-key]").forEach(function(cell){var key=cell.dataset.skillKey,sk=g?(g.player.skills&&g.player.skills[key]):null;var lvl=(D&&D.levelForXp&&sk)?D.levelForXp(sk.xp||0):1;var xp=sk?sk.xp||0:0,next=(D&&D.xpForLevel)?D.xpForLevel(lvl+1):100,cur=(D&&D.xpForLevel)?D.xpForLevel(lvl):0;var pct=next>cur?(xp-cur)/(next-cur)*100:100;var lv=cell.querySelector(".hi-sk-lv"),fl=cell.querySelector(".hi-sk-fill");if(lv)lv.textContent="Lv."+String(lvl).padStart(2,"0");if(fl)fl.style.width=Math.min(100,Math.max(0,pct))+"%";});}
function _updateEquipPane(){var g=_game(),D=window.UnkScape;// Update text readout column
document.querySelectorAll("[data-eq-slot]").forEach(function(el){if(el.dataset.hedVal!==undefined)return;var slot=el.dataset.eqSlot,eq=g?(g.player.equipment&&g.player.equipment[slot]):null;var def=eq&&D&&D.ITEMS&&D.ITEMS[eq];el.textContent=def?((def.icon||"")+" "+def.name):"—";});// Update paper-doll hed-val spans
document.querySelectorAll("[data-hed-val]").forEach(function(el){var slot=el.dataset.hedVal,eq=g?(g.player.equipment&&g.player.equipment[slot]):null;var def=eq&&D&&D.ITEMS&&D.ITEMS[eq];el.textContent=def?(def.icon||def.name.slice(0,3).toUpperCase()):"";el.closest(".hed-slot").classList.toggle("hed-has-item",!!def);});}
function _updateActionBar(){var g=_game(),D=window.UnkScape,slots=document.querySelectorAll("[data-action-slot]"),hotbar=g&&g.hotbar?g.hotbar.slots||[]:[];var inv=g&&g.systems?g.systems.inventory:null;slots.forEach(function(el,i){var id=hotbar[i],ico=el.querySelector(".ha-ico"),def=id&&D&&D.ITEMS&&D.ITEMS[id];if(!def){el.classList.add("empty");if(ico)ico.textContent="";el.title="";var q=el.querySelector(".ha-qty");if(q)q.remove();return;}el.classList.remove("empty");if(ico)ico.textContent=def.icon||"?";el.title=def.name||id;el.classList.toggle("sel",g&&g.hotbar&&g.hotbar.selected===i);var qty=inv?(inv.count(id)+(Object.values(g.player.equipment||{}).includes(id)?1:0)):0;var qEl=el.querySelector(".ha-qty");if(qty>1){if(!qEl){qEl=document.createElement("span");qEl.className="ha-qty";el.appendChild(qEl);}qEl.textContent="x"+qty;}else if(qEl){qEl.remove();}});}
function _drawRadar(){var ctx=_radarCtx;if(!ctx)return;var W=140,H=140,cx=70,cy=70,r=68;ctx.clearRect(0,0,W,H);ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fillStyle="rgba(8,6,14,0.85)";ctx.fill();ctx.strokeStyle="rgba(120,90,55,0.25)";ctx.lineWidth=1;[r*0.33,r*0.66,r].forEach(function(rr){ctx.beginPath();ctx.arc(cx,cy,rr,0,Math.PI*2);ctx.stroke();});ctx.beginPath();ctx.moveTo(cx,cy-r);ctx.lineTo(cx,cy+r);ctx.moveTo(cx-r,cy);ctx.lineTo(cx+r,cy);ctx.strokeStyle="rgba(120,90,55,0.18)";ctx.stroke();var g=_game();if(!g||!g.world)return;var D=window.UnkScape,p=g.player,px=p.x/D.TILE,py=p.y/D.TILE,scale=r/(D.WORLD?D.WORLD.w/10:120);ctx.fillStyle="#55cc77";(g.entities&&g.entities.npcs||[]).forEach(function(n){var dx=(n.x/D.TILE-px)*scale,dy=(n.y/D.TILE-py)*scale;if(dx*dx+dy*dy>r*r)return;ctx.beginPath();ctx.arc(cx+dx,cy+dy,3,0,Math.PI*2);ctx.fill();});ctx.fillStyle="#cc4444";(g.entities&&g.entities.enemies||[]).slice(0,60).forEach(function(e){var dx=(e.x/D.TILE-px)*scale,dy=(e.y/D.TILE-py)*scale;if(dx*dx+dy*dy>r*r)return;ctx.beginPath();ctx.arc(cx+dx,cy+dy,2,0,Math.PI*2);ctx.fill();});ctx.fillStyle="#ffffff";ctx.beginPath();ctx.arc(cx,cy,4,0,Math.PI*2);ctx.fill();var ang=(g.camera&&g.camera.targetAngle)||0;ctx.save();ctx.translate(cx,cy);ctx.rotate(ang);ctx.strokeStyle="#d4a84b";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(4,2);ctx.lineTo(0,-1);ctx.lineTo(-4,2);ctx.closePath();ctx.stroke();ctx.restore();}
function _renderLog(){var el=document.getElementById("hsr-log");if(!el)return;var lines=_sysTab==="all"?_logLines:_sysTab==="trade"?_logLines.filter(function(l){return l.senderClass==="trade";}):_logLines.filter(function(l){return l.senderClass!=="trade";});el.innerHTML=lines.map(function(line){return '<div class="hsr-line"><span class="hsr-line-sender '+line.senderClass+'">'+ _esc(line.sender)+':</span><span class="hsr-line-msg"> '+_esc(line.msg)+'</span></div>';}).join("");}
function _hookGameLog(){var attempts=0;_hookTimer=setInterval(function(){attempts++;var g=_game();if(g&&g.ui&&g.ui.log){var orig=g.ui.log.bind(g.ui);g.ui.log=function(msg,cls){orig(msg,cls);US.HUDSpec.log("",cls==="gold"?"npc":cls==="good"?"player":"system",msg);};clearInterval(_hookTimer);}if(attempts>30)clearInterval(_hookTimer);},500);}
function _esc(s){return String(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");}
})(window.UnkScape=window.UnkScape||{});
function _watchState(){var _lastState=null;setInterval(function(){var g=window.UnkScape&&window.UnkScape.game;var st=g?g.state:"menu";if(st===_lastState)return;_lastState=st;if(st==="play"){window.UnkScape.HUDSpec.show();window.UnkScape.HUDSpec.refresh();}else{window.UnkScape.HUDSpec.hide();}},250);}
(function(){function boot(){if(window.UnkScape&&window.UnkScape.HUDSpec)window.UnkScape.HUDSpec.init();}if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",boot);}else{boot();}})();
